### ISSUE TITLE
Not working on IOS 16 (Simulators)

### ISSUE THREAD

**Issue by alixumer** [dlutton/flutter_tts#346] opened 2022-10-02 20:34 UTC

**Comment by dlutton** [comment] 2022-10-02 21:54
@alixumer what exactly doesn't work on IOS 16?  I tested on my physical device on IOS 16 and it is working.

**Comment by therealjohnsummer** [comment] 2022-10-03 11:59
@dlutton Its the SIMULATORS that dont work ... i.e iOS 16.x simulators ... It works fine on iOS 13.x simulators as these ship with a default set of Language files. 

The issue is that there are no speech files found by default when you install the Simulator .. and thus there is no default (say) en_GB profile. You need to manually download the speech file onto the simulator and then there will be no issue ...

**Comment by dlutton** [comment] 2022-10-03 20:38
@therealjohnsummer okay thank you, I edited the title to better reflect the exact issue.

**Comment by fleoparra** [comment] 2022-10-12 18:42
Yes, I try to test on iOS 16.0 (Simulator) and 
```List<dynamic>? languages = await flutterTts.getLanguages; ```
returns null.

**Comment by dlutton** [comment] 2022-11-06 06:30
closing this as it's unrelated to this package.

@fleoparra for IOS 16 simulators, go settings -> Spoken content -> Voices -> Select any language and download.

**Closed by dlutton** 2022-11-06 06:30 UTC
