### ISSUE TITLE
Start handler not reached on Android

### ISSUE THREAD

**Issue by dbmessina** [dlutton/flutter_tts#362] opened 2022-12-12 19:37 UTC
## 🐛 Bug Report

The startHandler is not working right for Android as of 3.6.x. I observed this behavior in my own app and confirmed it with the flutter_tts example apps.

### Expected behavior

Upon calling speak(), the assigned start handler function should be called.

### Reproduction steps

Run the example app for flutter_tts 3.6.x on Android, enter some text, and press play. Playback begins, but "Playing" does not appear in the debug console as it should. It does appear with versions as late as 3.5.3. Reaching the start handler is not entirely broken though, as it will be called and playback will restart if you press play again before the first playback completes.

### Configuration

**Version:** 3.6.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by therealjohnsummer** [comment] 2022-12-15 19:56
Yes, broken from 3.6.x. Works fine however in iOS ... Its just that in Android the **Start Handler** is never invoked .... Ive tested in LIVE Android devices (10, 11 and Android 12) with the same behaviour. I upgraded from 3.3.3 which works perfectly and went straight to version 3.6.2 which yields the issue ....

**Comment by dlutton** [comment] 2022-12-16 08:04
thanks for the additional information @therealjohnsummer , I'll take a look into the issue.

**Comment by alexda12** [comment] 2022-12-21 16:33
@dbmessina - Did you manage to solve this ??

I have the exact same issue - the Start Handler fails to get called now in 3.6x under Android  & also iOS ....

@therealjohnsummer - Which version works for you ? Is there a later version that you managed to get this working in ? I tried 3.3.3 and this works but I need a later version.

**Comment by ssbaval** [comment] 2022-12-21 21:22
@dlutton I also have this bug and can confirm with @therealjohnsummer that this worked successfully in 3.3.3. 

@alexda12 I cannot find any workaround for this - the start handler simply isnt invoked.

**Comment by dlutton** [comment] 2022-12-21 22:51
@ssbaval @alexda12 @dbmessina the issue is with the pause functionality that was added for Android, I'm solving for anther approach towards pausing in Android which will fix this start handler issue.

**Comment by ssbaval** [comment] 2022-12-23 14:40
@dlutton Thanks for the confirmation here - when you are ready, I would be happy to test out your fix ...

**Comment by dlutton** [comment] 2022-12-25 03:56
great, I appreciate the assistance @ssbaval!

When you get a moment, do you mind testing out this branch before I merge in the fix.

```
flutter_tts:
    git:
      url: https://github.com/dlutton/flutter_tts.git
      ref: android-refactored-pause
```

**Comment by ssbaval** [comment] 2022-12-26 12:50
@dlutton That fix works. I tested on both Simulators and Live devices (iOS and Android).

For Android - I tested for Android 10, 11 and 12.

iOS I tested iOS 13.x and iOS 16.x

(Both iOS and Android testing was in RELEASE mode)

FYI - for Android 11 onwards - I didnt add any intent in my manifest , i.e

TextToSpeech.Engine.INTENT_ACTION_TTS_SERVICE  

and didnt have any issues  -  the docs mentions this intent needs to be added.

My only observation with this is fix is that in **Android** -  there is a noticeable delay before text is spoken - approx 2 secs delay. The first time the plugin is accessed , the delay is approx 7 secs. (I have made the plugin a factory service)

**Comment by dlutton** [comment] 2022-12-26 22:28
@ssbaval do you know if the delay existed for you in version 3.3.3?

**Comment by ssbaval** [comment] 2022-12-27 10:00
@dlutton  I can confirm that 3.3.3 works perfectly. There are no delays at all (This was the main reason why I didnt upgrade from this release) - There are no issues with this release for either iOS or Android (The only platforms my app currently supports).

**Comment by dlutton** [comment] 2022-12-31 10:02
@ssbaval please test with the latest version and if you're still experiencing issues regarding the delay, please open a new issue.  I'll close this one now that the fix has been merged in.  thanks again for assisting with testing.

**Closed by dlutton** 2022-12-31 10:02 UTC
Labels: bug
