### ISSUE TITLE
Since Flutter 2.8 flutter_tts won't build

### ISSUE THREAD

**Issue by dvorapa** [dlutton/flutter_tts#294] opened 2021-12-21 11:30 UTC
## 🐛 Bug Report

Since Flutter 2.8 you should declare your minSdkVersion in `local.properties` instead of `app/build.gradle`. But this is not recognized, build fails.

### Expected behavior
It should use the minSdkVersion from local.properties when building and not throw an error.

### Reproduction steps
```
$ flutter create testproject
$ nano testproject/pubspec.yaml  # add flutter_tts to dependencies
$ nano testproject/lib/main.dart  # use flutter_tts
$ nano testproject/android/local.properties  # fix minSdkVersion
$ flutter clean && flutter pub get && flutter run
Deleting build...                                                   15ms
Deleting .dart_tool...                                               1ms
Deleting .packages...                                                1ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            1ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in testproject...                         2 305ms
Launching lib/main.dart on HUAWEI CAM L21 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
/home/user/testproject/android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:flutter_tts] /home/user/testproject/build/flutter_tts/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.tundralabs.fluttertts" to force usage (may lead to runtime failures)
         *********************************************************
WARNING: This version of flutter_tts will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:flutter_tts] /home/user/testproject/build/flutter_tts/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.tundralabs.fluttertts" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 34s
Running Gradle task 'assembleDebug'...                             96,6s

The plugin flutter_tts requires a higher Android SDK version.
Fix this issue by adding the following to the file
/home/user/testproject/android/app/build.gradle:
android {
  defaultConfig {
    minSdkVersion 21
  }
}


Note that your app won't be available to users running Android SDKs below 21.
Alternatively, try to find a version of this plugin that supports these lower
versions of the Android SDK.
Exception: Gradle task assembleDebug failed with exit code 1
```

### Configuration
```
$ flutter --version
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (5 days ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Arch Linux 5.15.10-arch1-1, locale
    cs_CZ.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2020.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Version:** 3.2.4

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by sp-sivaprasad** [comment] 2021-12-23 05:00
same issue here

WARNING: This version of flutter_tts will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.0-rc01.
     AAR metadata file: C:\Users\HP\.gradle\caches\transforms-2\files-2.1\3d98eb3bd48e56d0131874db88bb1279\work-runtime-2.7.0-rc01\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by dlutton** [comment] 2021-12-23 19:53
@dvorapa it appears something you're using is using an android sdk version earlier than 21.   This package requires a minimum of 21.

```
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:flutter_tts] /mnt/Data/Tvorba/stepslow/build/flutter_tts/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.tundralabs.fluttertts" to force usage (may lead to runtime failures)
```

**Comment by dlutton** [comment] 2021-12-23 19:57
@sp-sivaprasad are you using the latest 3.2.4 flutter_tts version?  Your error seems to be unrelated.  Try using the latest version and running flutter clean.

**Comment by dvorapa** [comment] 2021-12-23 21:49
> @dvorapa it appears something you're using is using an android sdk version earlier than 21. This package requires a minimum of 21.
> 
> ```
> Execution failed for task ':app:processDebugMainManifest'.
> > Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:flutter_tts] /mnt/Data/Tvorba/stepslow/build/flutter_tts/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
>   	Suggestion: use a compatible library with a minSdk of at most 16,
>   		or increase this project's minSdk version to at least 21,
>   		or use tools:overrideLibrary="com.tundralabs.fluttertts" to force usage (may lead to runtime failures)
> ```

I don't, I have minSdk set to 21, only flutter_tts has some issue recognizing my prefference

**Comment by dvorapa** [comment] 2021-12-23 21:55
Have you tried my reproduction steps with Flutter 2.8+?

**Comment by dlutton** [comment] 2021-12-23 23:44
@dvorapa Oh my apologies as I haven't tested the local properties change.  Looks like it's issue that's been addressed in the flutter repo https://github.com/flutter/flutter/issues/95533.

**Comment by sp-sivaprasad** [comment] 2021-12-24 01:05
I updated to flutter_tts 3.3.1 and previous error was gone.  but now another issue showed up

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\HP\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_tts-3.3.1\android\build.gradle' line: 23


* What went wrong:
A problem occurred configuring project ':flutter_tts'.
> Could not create task ':flutter_tts:compileDebugJavaWithJavac'.
   > Could not get unknown property 'args' for task ':flutter_tts:compileDebugJavaWithJavac' of type org.gradle.api.tasks.compile.JavaCompile.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by dlutton** [comment] 2021-12-24 03:48
@sp-sivaprasad that's my fault, please try the latest 3.3.2 version which includes the missing args param I accidentally removed.

**Comment by sp-sivaprasad** [comment] 2021-12-24 04:47
@dlutton 

Thank you. issue gone :)

**Comment by dlutton** [comment] 2021-12-24 20:18
@dvorapa I'm closing this since it's being addressed in the flutter repo.

**Closed by dlutton** 2021-12-24 20:18 UTC

**Comment by dvorapa** [comment] 2021-12-25 19:13
Sure, I'll follow upstream issue then. Thank you for your investigation!!
