### ISSUE TITLE
Conversion Error

### ISSUE THREAD

**Issue by alnaughty** [dlutton/flutter_tts#417] opened 2023-08-28 06:51 UTC
## 🐛 Bug Report

Cannot convert value of type 'String' to expected argument type 'URL' ../../../.pub-cache/hosted/pub.dev/flutter_tts-3.8.0/ios/Classes/SwiftFlutterTtsPlugin.swift:198:26

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by dlutton** [comment] 2023-08-28 07:07
duplicate of https://github.com/dlutton/flutter_tts/issues/416

**Closed by dlutton** 2023-08-28 07:07 UTC
Labels: bug
